version: "3"

vars:
  ANSIBLE_OPTION: --clean --onefile --noconfirm --ascii --strip --add-data ansible/ansible/config/base.yml:ansible/config --add-data ansible/ansible/config/ansible_builtin_runtime.yml:ansible/config
  ANSIBLE_EXTRAS_PIP: uuid

tasks:
  default:
    cmds:
      - task --list-all

  pip-install:
    cmds:
      - pip install pyinstaller

  clean:
    cmds:
      - rm -rf .tmp/*
      - find . -regex '^.*\(__pycache__\|\.py[co]\)$' -delete

  ansible-download:
    cmds:
      - wget https://github.com/ownport/portable-ansible/releases/download/v0.5.0/portable-ansible-v0.5.0-py3.tar.bz2 -O ansible.tar.bz2
      - tar -xjf ansible.tar.bz2
      - rm -rf ansible.tar.bz2
      - for l in config console doc galaxy inventory playbook pull vault;do ln -s ansible ansible-$l;done
      - pip install -t ansible/extras {{.ANSIBLE_EXTRAS_PIP}}
    dir: .tmp
    status:
      - python ansible localhost -m ping

  ansible-build:
    cmds:
      - pyinstaller ansible/__main__.py -n ansible --clean --onefile --noconfirm --ascii --strip
      - pyinstaller ansible-config/__main__.py -n ansible-config {{.ANSIBLE_OPTION}} --add-data ansible/ansible/cli/config.py:ansible/cli
      - pyinstaller ansible-console/__main__.py -n ansible-console {{.ANSIBLE_OPTION}} --add-data ansible/ansible/cli/console.py:ansible/cli
      - pyinstaller ansible-doc/__main__.py -n ansible-doc {{.ANSIBLE_OPTION}} --add-data ansible/ansible/cli/doc.py:ansible/cli
      - pyinstaller ansible-galaxy/__main__.py -n ansible-galaxy {{.ANSIBLE_OPTION}} --add-data ansible/ansible/cli/galaxy.py:ansible/cli
      - pyinstaller ansible-inventory/__main__.py -n ansible-inventory {{.ANSIBLE_OPTION}} --add-data ansible/ansible/cli/inventory.py:ansible/cli
      - pyinstaller ansible-playbook/__main__.py -n ansible-playbook {{.ANSIBLE_OPTION}} --add-data ansible/ansible/cli/playbook.py:ansible/cli
      - pyinstaller ansible-pull/__main__.py -n ansible-pull {{.ANSIBLE_OPTION}} --add-data ansible/ansible/cli/pull.py:ansible/cli
      - pyinstaller ansible-vault/__main__.py -n ansible-vault {{.ANSIBLE_OPTION}} --add-data ansible/ansible/cli/vault.py:ansible/cli
    dir: .tmp

  go-test:
    cmds:
      - TF_ACC=1 go test ./... -v $(TESTARGS) -timeout 120m
