version: "3"

vars:
  ANSIBLE_BUILD_OPTION: --clean --onefile --noconfirm --collect-all pty --collect-all email --add-data ansible/ansible:ansible # --ascii --strip

tasks:
  default:
    cmds:
      - task --list-all

  pip-install:
    cmds:
      - pip install pyinstaller

  ansible-build:
    cmds:
      - pyinstaller ansible/__main__.py -n ansiblex {{.ANSIBLE_BUILD_OPTION}}
      - for l in config console doc galaxy inventory playbook pull vault;do pyinstaller ansible-$l/__main__.py -n ansible-$l {{.ANSIBLE_BUILD_OPTION}};done
    dir: tools/ansible-portable

  docker-pyinstaller-build:
    cmds:
      - docker build -t pepodev/pyinstaller .
    dir: tools/ansible-portable

  ansible-build-docker:
    cmds:
      - docker run -it --rm -v $PWD:/opt pepodev/pyinstaller "pyinstaller ansible/__main__.py -n ansiblex {{.ANSIBLE_BUILD_OPTION}}"
      - docker run -it --rm -v $PWD:/opt pepodev/pyinstaller "for l in config console doc galaxy inventory playbook pull vault;do pyinstaller ansible-$l/__main__.py -n ansible-$l {{.ANSIBLE_BUILD_OPTION}};done"
    dir: tools/ansible-portable

  go-test:
    cmds:
      - TF_ACC=1 go test ./... -v $(TESTARGS) -timeout 120m
